export const SITE = {
  website: "https://mola1129.dev",
  author: "mola1129",
  profile: "https://github.com/mola1129",
  desc: "Hi there",
  title: "Mola1129 Dev",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 4,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: false,
  showBackButton: true,
  editPost: {
    enabled: true,
    text: "GitHubで編集を提案",
    url: "https://github.com/mola1129/blog/edit/main/",
  },
  dynamicOgImage: true,
  lang: "ja",
  timezone: "Asia/Tokyo",
} as const;
